### ISSUE TITLE
feat: import users endpoint 

### ISSUE THREAD

**Issue by saidabdul80** [cs-dept-ibbul/vlab#127]
please use the interface to make the endpoint. Note data data will not be coming in csv and they are required like faculty_id and department_id, role_id
![user upload interface](https://user-images.githubusercontent.com/42839808/116874673-9b02b700-ac11-11eb-84ec-e17ffc2a225b.png)

**Comment by bynalab** [comment]
I think we already have the upload students endpoint, please check and confirm.

**Comment by saidabdul80** [comment]
actually sir this is different. the former will work for instructor uploading student. the new feat should work for admin as they have different requirment like
`courses` in **instructor** end
**and** 
`faculty,`  `role`  in **admin** end 
However for now we are working on the admin end
