### ISSUE TITLE
Feat: create experiment endpoint

### ISSUE THREAD

**Issue by saidabdul80** [cs-dept-ibbul/vlab#87]
### Experiment_tbl columns
```
title varchar,
experiment_number,
video_url,
theory,
aim,
resources,
exercise,
exercise varchar(3000),
aparatus,
procedure,
experiment_url,
config varchar(11), //or Enum(0,1) most preferable 0 as default
```
@Auwalms @bynalab @abdullahikawu

**Comment by bynalab** [comment]
Is this all the column you'll be needing for the experiment table?

**Comment by Auwalms** [comment]
@saidabdul80 why do we need experiment_url? Also, is video_url same as experiment_mock? Else can you clarify?
