### ISSUE TITLE
feat: List of all student by course id. Endpoint

### ISSUE THREAD

**Issue by saidabdul80** [cs-dept-ibbul/vlab#99]
with experiment details
for example

```
   students_enrolled ={
       { id, fname, lname, ......, },
       ....
   }

```

**Comment by bynalab** [comment]
Duplicate of https://github.com/cs-dept-ibbul/vlab/issues/80, which i think commit https://github.com/cs-dept-ibbul/vlab/commit/2a7dbca9894ed2c7a8bc31b2ebdc2fb0a017d7e5 handled.
